development:
  adapter: redis
  url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %>
  channel_prefix: root_sim_development


test:
  adapter: redis
  url: <%= Rails.application.credentials.redis_url %>
  channel_prefix: your_app_test

production:
  adapter: redis
  url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %>
  channel_prefix: root_sim_production
